# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore EnumConstraints.Fody.sln
      
    - name: Build
      run: dotnet build --no-restore EnumConstraints.Fody.sln

    - name: Test
      run:  dotnet-coverage collect dotnet test --no-build --verbosity normal ./tests/EnumConstraints.Fody.Tests/EnumConstraints.Fody.Tests.csproj
    
    - name: Create code coverage report
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        dotnet-coverage merge -f cobertura .\output.coverage
        reportgenerator -reports:./output.cobertura.xml -targetdir:CodeCoverage -reporttypes:'MarkdownSummaryGithub;Cobertura' -verbosity Off -assemblyfilters:'+EnumConstraints.Fody;+EnumConstraints'
        cat CodeCoverage/SummaryGithub.md >> $GITHUB_STEP_SUMMARY  


